# Generated by Django 3.0.3 on 2021-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('content', models.TextField()),
                ('img_url', models.CharField(max_length=264)),
            ],
        ),
    ]
